In [1]:
# import dependencies
import pandas as pd

In [18]:
df1 = pd.read_csv('JC-20210611-citibike-tripdata.csv')
df1 = pd.DataFrame(df1)
df1.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual

In [20]:
df2 = pd.read_csv('JC-20210715-citibike-tripdata.csv')
df2 = pd.DataFrame(df2)
df2.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,6457BC38526A4187,docked_bike,2021-06-21 10:19:04,2021-06-21 10:26:28,Lafayette Park,JC078,City Hall,JC003,40.713463,-74.062858,40.717732,-74.043845,member
1,508AC0C37B2BE1A8,docked_bike,2021-06-05 10:12:18,2021-06-05 10:27:10,Mama Johnson Field - 4 St & Jackson St,HB404,Bloomfield St & 15 St,HB203,40.743139,-74.040040,40.754530,-74.026580,member
2,A1AD52779E13308C,docked_bike,2021-06-04 15:42:35,2021-06-04 15:54:28,Lincoln Park,JC053,Grand St,JC102,40.724605,-74.078405,40.715178,-74.037683,member
3,DA8AA7083ACCA940,docked_bike,2021-06-03 18:07:42,2021-06-03 19:09:26,Columbus Park - Clinton St & 9 St,HB501,Columbus Park - Clinton St & 9 St,HB501,40.748161,-74.032453,40.748161,-74.032453,casual
4,BF8DB08AEF78C8D1,docked_bike,2021-06-05 15:39:56,2021-06-05 16:16:09,Columbus Park - Clinton St & 9 St,HB501,Columbus Park - Clinton St & 9 St,HB501,40.748161,-74.032453,40.748161,-74.032453,casual

In [21]:
df3 = pd.read_csv('JC-20210814-citibike-tripdata.csv')
df3 = pd.DataFrame(df3)
df3.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,2F01C15ECE379AE7,classic_bike,2021-07-31 13:53:26,2021-07-31 14:47:00,Bergen Ave & Stegman St,JC108,South Waterfront Walkway - Sinatra Dr & 1 St,HB103,40.706575,-74.086701,40.736982,-74.027781,member
1,CF7E2039ACB179C2,classic_bike,2021-07-17 19:06:01,2021-07-17 19:20:07,Bergen Ave & Stegman St,JC108,Baldwin at Montgomery,JC020,40.706575,-74.086701,40.723659,-74.064194,member
2,9375052379DE50FC,classic_bike,2021-07-08 19:54:34,2021-07-08 20:43:06,Columbus Dr at Exchange Pl,JC106,Liberty Light Rail,JC052,40.716870,-74.032810,40.711242,-74.055701,member
3,EF77D67D538E108E,classic_bike,2021-07-18 20:21:15,2021-07-18 20:28:23,Columbus Dr at Exchange Pl,JC106,Warren St,JC006,40.716870,-74.032810,40.721124,-74.038051,member
4,3550C64E6994B8BC,classic_bike,2021-07-08 18:19:07,2021-07-08 18:24:48,Columbus Dr at Exchange Pl,JC106,Warren St,JC006,40.716870,-74.032810,40.721124,-74.038051,member

In [22]:
df4 = pd.read_csv('JC-20210908-citibike-tripdata.csv')
df4 = pd.DataFrame(df4)
df4.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,5CABAE380FF3C7E0,classic_bike,2021-08-06 07:02:02,2021-08-06 07:28:56,Dey St,JC065,Stevens - River Ter & 6 St,HB602,40.737711,-74.066921,40.743133,-74.026989,casual
1,0C820F4E9256B5BB,classic_bike,2021-08-15 19:48:51,2021-08-15 20:04:45,Grand St & 2 St,HB405,Jersey & 3rd,JC074,40.739130,-74.036180,40.723332,-74.045953,member
2,F33B1B767F55A2BC,classic_bike,2021-08-26 17:14:58,2021-08-26 17:20:13,Grand St & 2 St,HB405,7 St & Monroe St,HB304,40.739130,-74.036180,40.746413,-74.037977,casual
3,EF7A1541C2302EEF,classic_bike,2021-08-12 12:58:22,2021-08-12 13:04:07,Dey St,JC065,Sip Ave,JC056,40.737711,-74.066921,40.730897,-74.063913,member
4,74DEC24E4C66BA01,classic_bike,2021-08-04 20:59:45,2021-08-04 21:10:39,Glenwood Ave,JC094,Pershing Field,JC024,40.727551,-74.071061,40.742677,-74.051789,member

In [23]:
df5 = pd.read_csv('JC-20211004-citibike-tripdata.csv')
df5 = pd.DataFrame(df5)
df5.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,228F2E2FEBFBF843,classic_bike,2021-09-11 16:03:10,2021-09-11 16:20:57,Jersey & 6th St,JC027,Astor Place,JC077,40.725289,-74.045572,40.719282,-74.071262,casual
1,DCDBDC0A5178BAB5,classic_bike,2021-09-14 17:27:50,2021-09-14 17:34:18,Jersey & 6th St,JC027,Marin Light Rail,JC013,40.725289,-74.045572,40.714584,-74.042817,member
2,DD7AD7B81588187B,docked_bike,2021-09-04 20:29:34,2021-09-04 20:41:17,12 St & Sinatra Dr N,HB201,4 St & Grand St,HB301,40.750604,-74.024020,40.742258,-74.035111,casual
3,4D3CFEEB6E3E514B,classic_bike,2021-09-16 17:26:37,2021-09-16 17:32:48,Jersey & 6th St,JC027,Marin Light Rail,JC013,40.725289,-74.045572,40.714584,-74.042817,member
4,D05FC6DDE1112F08,classic_bike,2021-09-16 18:05:35,2021-09-16 18:16:02,Jersey & 6th St,JC027,Columbus Dr at Exchange Pl,JC106,40.725289,-74.045572,40.716870,-74.032810,member

In [24]:
df6 = pd.read_csv('JC-20211105-citibike-tripdata.csv')
df6 = pd.DataFrame(df6)
df6.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0FA0B0B972A68AAB,classic_bike,2021-10-19 06:08:46,2021-10-19 06:11:26,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,member
1,0702BED6EB379838,classic_bike,2021-10-16 12:08:29,2021-10-16 12:13:29,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,member
2,A8810ECCC69E2866,classic_bike,2021-10-29 12:29:49,2021-10-29 12:34:49,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,member
3,C9A0FF2B82237FFA,classic_bike,2021-10-08 12:36:21,2021-10-08 12:40:55,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,member
4,7DFDEB8EF4CAB15C,classic_bike,2021-10-14 06:54:51,2021-10-14 07:01:14,Glenwood Ave,JC094,Sip Ave,JC056,40.727551,-74.071061,40.730897,-74.063913,casual

In [25]:
df7 = pd.read_csv('JC-20211208-citibike-tripdata.csv')
df7= pd.DataFrame(df7)
df7.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,DF35F0CFE02F24FA,classic_bike,2021-11-10 07:59:48,2021-11-10 08:12:54,Bergen Ave & Stegman St,JC108,McGinley Square,JC055,40.706575,-74.086701,40.725340,-74.067622,casual
1,4D166A3D049BA4F7,classic_bike,2021-11-03 09:41:50,2021-11-03 09:58:29,Bergen Ave & Stegman St,JC108,Lafayette Park,JC078,40.706575,-74.086701,40.713464,-74.062859,casual
2,F4BA689777358AD3,classic_bike,2021-11-10 09:03:46,2021-11-10 09:08:36,Washington St,JC098,Columbus Dr at Exchange Pl,JC106,40.724294,-74.035483,40.716870,-74.032810,member
3,9B9A296982C436CC,classic_bike,2021-11-09 17:00:38,2021-11-09 17:44:40,JC Medical Center,JC011,Grove St PATH,JC005,40.716540,-74.049638,40.719586,-74.043117,member
4,EBC2B8A56E6F168F,classic_bike,2021-11-25 07:15:51,2021-11-25 07:22:06,JC Medical Center,JC011,Hamilton Park,JC009,40.716540,-74.049638,40.727596,-74.044247,member

In [26]:
frames = [df1, df2, df3, df4, df5, df6, df7]
merged = pd.concat(frames)

In [28]:
merged

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60056,2CCA05843D499F18,classic_bike,2021-11-18 12:12:29,2021-11-18 12:17:44,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.735208,-74.046964,40.735938,-74.030305,member
60057,CD649E367FF12492,classic_bike,2021-11-26 21:49:49,2021-11-26 21:57:33,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.735208,-74.046964,40.735938,-74.030305,member
60058,749628C550B1262D,classic_bike,2021-11-29 16:20:36,2021-11-29 16:25:13,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.735208,-74.046964,40.735938,-74.030305,member
60059,ECC00F7D85F55D63,classic_bike,2021-11-02 08:25:46,2021-11-02 08:31:29,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.735208,-74.046964,40.735938,-74.030305,member
60060,5384882522AA003C,classic_bike,2021-11-09 15:07:55,2021-11-09 15:15:17,Hoboken Ave at Monmouth St,JC105,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.735208,-74.046964,40.735938,-74.030305,member

In [29]:
merged.to_csv('citibike.csv', index=False)